version: "3.9"

services:
  db:
    container_name: db-with-postgis
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: rewarder
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
